// src/components/header/navbar.svelte
<script>
	import NavItem from './nav-item.svelte';
</script>

<nav class="items-center justify-between md:flex">
	<ul
		class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white"
	>
		<li><NavItem href="/">Home</NavItem></li>
		<li><NavItem href="/play">Play</NavItem></li>
		<li><NavItem href="/analyze">Analyze</NavItem></li>
		<li><NavItem href="/notation">Notation</NavItem></li>
	</ul>
</nav>

// src/app/navbar/navbar.component.ts
import { Component } from "@angular/core";

import { faChessKnight } from "@fortawesome/free-solid-svg-icons";
import { faGithubAlt } from "@fortawesome/free-brands-svg-icons";

@Component({
  selector: "app-navbar",
  templateUrl: "./navbar.component.html",
  styleUrls: ["./navbar.component.scss"],
})
export class NavbarComponent {
  faChessKnight = faChessKnight;
  faGithubAlt = faGithubAlt;

  navbarActive: boolean = false;

  toggleNavbar() {
    this.navbarActive = !this.navbarActive;
  }
}

<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <a routerLink="/home" class="flex items-center">
      <fa-icon
        [icon]="faChessKnight"
        class="text-blue-600 text-3xl ml-2 mr-3 sm:text-4xl sm:ml-0"
      ></fa-icon>
      <span class="self-center text-xl font-semibold whitespace-nowrap"
        >Xadrez</span
      >
    </a>
    <div class="flex md:order-2">
      <button
        type="button"
        class="flex text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0"
      >
        <fa-icon [icon]="faGithubAlt" class="mr-2 text-base"></fa-icon>
        <a href="https://github.com/jovialen/xadrez" target="_blank"
          >On GitHub</a
        >
      </button>
      <button
        type="button"
        class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
        (click)="toggleNavbar()"
        aria-controls="navbar-links"
        aria-expanded="false"
      >
        <span class="sr-only">Toggle navigation</span>
        <fa-icon
          [icon]="faBarsStaggered"
          class="nav-toggle"
          [class.hidden]="!navbarActive"
        ></fa-icon>
        <fa-icon
          [icon]="faXmark"
          class="nav-toggle"
          [class.hidden]="navbarActive"
        ></fa-icon>
      </button>
    </div>
    <div
      class="items-center justify-between w-full md:flex md:w-auto md:order-1"
      [class.hidden]="navbarActive"
      id="navbar-links"
    >
      <ul
        class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white"
      >
        <li>
          <a
            routerLinkActive="active-route"
            ariaCurrentWhenActive="page"
            routerLink="/home"
            class="nav-item"
            >Home</a
          >
        </li>
        <li>
          <a
            routerLinkActive="active-route"
            ariaCurrentWhenActive="page"
            routerLink="/play"
            class="nav-item"
            >Play</a
          >
        </li>
        <li>
          <a
            routerLinkActive="active-route"
            ariaCurrentWhenActive="page"
            routerLink="/analyze"
            class="nav-item"
            >Analyze</a
          >
        </li>
        <li>
          <a
            routerLinkActive="active-route"
            ariaCurrentWhenActive="page"
            routerLink="/notation"
            class="nav-item"
            >Notation</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>
